// source: app.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.app_service.BacktestRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.app_service.BacktestRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.app_service.BacktestRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.app_service.BacktestRequest.displayName = 'proto.app_service.BacktestRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.app_service.BacktestRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.app_service.BacktestRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.app_service.BacktestRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.app_service.BacktestRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tickera: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tickerb: jspb.Message.getFieldWithDefault(msg, 2, ""),
    daysrange: jspb.Message.getFieldWithDefault(msg, 3, 0),
    daysoffset: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.app_service.BacktestRequest}
 */
proto.app_service.BacktestRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.app_service.BacktestRequest;
  return proto.app_service.BacktestRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.app_service.BacktestRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.app_service.BacktestRequest}
 */
proto.app_service.BacktestRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTickera(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTickerb(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDaysrange(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDaysoffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.app_service.BacktestRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.app_service.BacktestRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.app_service.BacktestRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.app_service.BacktestRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTickera();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTickerb();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDaysrange();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getDaysoffset();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string tickerA = 1;
 * @return {string}
 */
proto.app_service.BacktestRequest.prototype.getTickera = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.app_service.BacktestRequest} returns this
 */
proto.app_service.BacktestRequest.prototype.setTickera = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string tickerB = 2;
 * @return {string}
 */
proto.app_service.BacktestRequest.prototype.getTickerb = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.app_service.BacktestRequest} returns this
 */
proto.app_service.BacktestRequest.prototype.setTickerb = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 daysRange = 3;
 * @return {number}
 */
proto.app_service.BacktestRequest.prototype.getDaysrange = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.app_service.BacktestRequest} returns this
 */
proto.app_service.BacktestRequest.prototype.setDaysrange = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 daysOffset = 4;
 * @return {number}
 */
proto.app_service.BacktestRequest.prototype.getDaysoffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.app_service.BacktestRequest} returns this
 */
proto.app_service.BacktestRequest.prototype.setDaysoffset = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


