// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: quant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegressionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegressionRequest) Reset() {
	*x = RegressionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionRequest) ProtoMessage() {}

func (x *RegressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionRequest.ProtoReflect.Descriptor instead.
func (*RegressionRequest) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{0}
}

func (x *RegressionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegressionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Submitted bool   `protobuf:"varint,2,opt,name=submitted,proto3" json:"submitted,omitempty"`
}

func (x *RegressionResult) Reset() {
	*x = RegressionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegressionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionResult) ProtoMessage() {}

func (x *RegressionResult) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionResult.ProtoReflect.Descriptor instead.
func (*RegressionResult) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{1}
}

func (x *RegressionResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegressionResult) GetSubmitted() bool {
	if x != nil {
		return x.Submitted
	}
	return false
}

var File_quant_proto protoreflect.FileDescriptor

var file_quant_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x23, 0x0a, 0x11,
	0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x40, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x74, 0x65, 0x64, 0x32, 0x61, 0x0a, 0x0c, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x2e, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quant_proto_rawDescOnce sync.Once
	file_quant_proto_rawDescData = file_quant_proto_rawDesc
)

func file_quant_proto_rawDescGZIP() []byte {
	file_quant_proto_rawDescOnce.Do(func() {
		file_quant_proto_rawDescData = protoimpl.X.CompressGZIP(file_quant_proto_rawDescData)
	})
	return file_quant_proto_rawDescData
}

var file_quant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quant_proto_goTypes = []interface{}{
	(*RegressionRequest)(nil), // 0: quant_service.RegressionRequest
	(*RegressionResult)(nil),  // 1: quant_service.RegressionResult
}
var file_quant_proto_depIdxs = []int32{
	0, // 0: quant_service.QuantService.Regression:input_type -> quant_service.RegressionRequest
	1, // 1: quant_service.QuantService.Regression:output_type -> quant_service.RegressionResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quant_proto_init() }
func file_quant_proto_init() {
	if File_quant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegressionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegressionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quant_proto_goTypes,
		DependencyIndexes: file_quant_proto_depIdxs,
		MessageInfos:      file_quant_proto_msgTypes,
	}.Build()
	File_quant_proto = out.File
	file_quant_proto_rawDesc = nil
	file_quant_proto_goTypes = nil
	file_quant_proto_depIdxs = nil
}
