# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quant.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquant.proto\x12\rquant_service\"\x18\n\nJobRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\tJobResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsubmitted\x18\x02 \x01(\x08\x32\x9e\x01\n\x0cQuantService\x12\x46\n\rCointegration\x12\x19.quant_service.JobRequest\x1a\x18.quant_service.JobResult\"\x00\x12\x46\n\rOLSRegression\x12\x19.quant_service.JobRequest\x1a\x18.quant_service.JobResult\"\x00\x42\x08Z\x06proto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006proto/'
  _globals['_JOBREQUEST']._serialized_start=30
  _globals['_JOBREQUEST']._serialized_end=54
  _globals['_JOBRESULT']._serialized_start=56
  _globals['_JOBRESULT']._serialized_end=98
  _globals['_QUANTSERVICE']._serialized_start=101
  _globals['_QUANTSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
