// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/quant.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QuantService_RollingOrdinaryLeastSquares_FullMethodName = "/quant_service.QuantService/RollingOrdinaryLeastSquares"
	QuantService_Unary_FullMethodName                       = "/quant_service.QuantService/Unary"
)

// QuantServiceClient is the client API for QuantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuantServiceClient interface {
	RollingOrdinaryLeastSquares(ctx context.Context, opts ...grpc.CallOption) (QuantService_RollingOrdinaryLeastSquaresClient, error)
	Unary(ctx context.Context, in *RequestTest, opts ...grpc.CallOption) (*ResponseTest, error)
}

type quantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantServiceClient(cc grpc.ClientConnInterface) QuantServiceClient {
	return &quantServiceClient{cc}
}

func (c *quantServiceClient) RollingOrdinaryLeastSquares(ctx context.Context, opts ...grpc.CallOption) (QuantService_RollingOrdinaryLeastSquaresClient, error) {
	stream, err := c.cc.NewStream(ctx, &QuantService_ServiceDesc.Streams[0], QuantService_RollingOrdinaryLeastSquares_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &quantServiceRollingOrdinaryLeastSquaresClient{stream}
	return x, nil
}

type QuantService_RollingOrdinaryLeastSquaresClient interface {
	Send(*RollingOrdinaryLeastSquaresDatapoint) error
	CloseAndRecv() (*RollingOrdinaryLeastSquaresResult, error)
	grpc.ClientStream
}

type quantServiceRollingOrdinaryLeastSquaresClient struct {
	grpc.ClientStream
}

func (x *quantServiceRollingOrdinaryLeastSquaresClient) Send(m *RollingOrdinaryLeastSquaresDatapoint) error {
	return x.ClientStream.SendMsg(m)
}

func (x *quantServiceRollingOrdinaryLeastSquaresClient) CloseAndRecv() (*RollingOrdinaryLeastSquaresResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RollingOrdinaryLeastSquaresResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *quantServiceClient) Unary(ctx context.Context, in *RequestTest, opts ...grpc.CallOption) (*ResponseTest, error) {
	out := new(ResponseTest)
	err := c.cc.Invoke(ctx, QuantService_Unary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuantServiceServer is the server API for QuantService service.
// All implementations must embed UnimplementedQuantServiceServer
// for forward compatibility
type QuantServiceServer interface {
	RollingOrdinaryLeastSquares(QuantService_RollingOrdinaryLeastSquaresServer) error
	Unary(context.Context, *RequestTest) (*ResponseTest, error)
	mustEmbedUnimplementedQuantServiceServer()
}

// UnimplementedQuantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuantServiceServer struct {
}

func (UnimplementedQuantServiceServer) RollingOrdinaryLeastSquares(QuantService_RollingOrdinaryLeastSquaresServer) error {
	return status.Errorf(codes.Unimplemented, "method RollingOrdinaryLeastSquares not implemented")
}
func (UnimplementedQuantServiceServer) Unary(context.Context, *RequestTest) (*ResponseTest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedQuantServiceServer) mustEmbedUnimplementedQuantServiceServer() {}

// UnsafeQuantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantServiceServer will
// result in compilation errors.
type UnsafeQuantServiceServer interface {
	mustEmbedUnimplementedQuantServiceServer()
}

func RegisterQuantServiceServer(s grpc.ServiceRegistrar, srv QuantServiceServer) {
	s.RegisterService(&QuantService_ServiceDesc, srv)
}

func _QuantService_RollingOrdinaryLeastSquares_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QuantServiceServer).RollingOrdinaryLeastSquares(&quantServiceRollingOrdinaryLeastSquaresServer{stream})
}

type QuantService_RollingOrdinaryLeastSquaresServer interface {
	SendAndClose(*RollingOrdinaryLeastSquaresResult) error
	Recv() (*RollingOrdinaryLeastSquaresDatapoint, error)
	grpc.ServerStream
}

type quantServiceRollingOrdinaryLeastSquaresServer struct {
	grpc.ServerStream
}

func (x *quantServiceRollingOrdinaryLeastSquaresServer) SendAndClose(m *RollingOrdinaryLeastSquaresResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *quantServiceRollingOrdinaryLeastSquaresServer) Recv() (*RollingOrdinaryLeastSquaresDatapoint, error) {
	m := new(RollingOrdinaryLeastSquaresDatapoint)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _QuantService_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantServiceServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantService_Unary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantServiceServer).Unary(ctx, req.(*RequestTest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuantService_ServiceDesc is the grpc.ServiceDesc for QuantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quant_service.QuantService",
	HandlerType: (*QuantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _QuantService_Unary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RollingOrdinaryLeastSquares",
			Handler:       _QuantService_RollingOrdinaryLeastSquares_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/quant.proto",
}
