# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quant.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquant.proto\x12\rquant_service\"2\n$RollingOrdinaryLeastSquaresDatapoint\x12\n\n\x02id\x18\x01 \x01(\x03\"/\n!RollingOrdinaryLeastSquaresResult\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x99\x01\n\x0cQuantService\x12\x88\x01\n\x1bRollingOrdinaryLeastSquares\x12\x33.quant_service.RollingOrdinaryLeastSquaresDatapoint\x1a\x30.quant_service.RollingOrdinaryLeastSquaresResult\"\x00(\x01\x42\x08Z\x06proto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006proto/'
  _globals['_ROLLINGORDINARYLEASTSQUARESDATAPOINT']._serialized_start=30
  _globals['_ROLLINGORDINARYLEASTSQUARESDATAPOINT']._serialized_end=80
  _globals['_ROLLINGORDINARYLEASTSQUARESRESULT']._serialized_start=82
  _globals['_ROLLINGORDINARYLEASTSQUARESRESULT']._serialized_end=129
  _globals['_QUANTSERVICE']._serialized_start=132
  _globals['_QUANTSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
